<<<<<<<< HEAD:.github/workflows/python-container-app-AutoDeployTrigger-7c89ee6a-d4cd-469a-916e-eb096966eb96.yml
name: Trigger auto deployment for python-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/python-container-app-AutoDeployTrigger-7c89ee6a-d4cd-469a-916e-eb096966eb96.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PYTHONCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: lenvappacr.azurecr.io
          registryUsername: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: python-container-app
          resourceGroup: pythoncontainer-rg
          imageToBuild: lenvappacr.azurecr.io/python-container-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

========
name: Trigger auto deployment for python-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/python-container-app.yml'

  # Allow manual trigger 
  workflow_dispatch:

# Special permissions required for OIDC authentication
permissions:
    id-token: write
    contents: read
    #pull-requests: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PYTHONCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: lenvappacr.azurecr.io
          registryUsername: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: python-container-app
          resourceGroup: pythoncontainer-rg
          imageToBuild: lenvappacr.azurecr.io/python-container-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

>>>>>>>> f585611 (renaming):.github/workflows/python-container-app.yml
